// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadJQResult(arg1:string):Promise<void>;

export function GetInitialContent():Promise<string>;

export function Query(arg1:string,arg2:string,arg3:main.JQFlags):Promise<string>;
