// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInitialContent() {
  return window['go']['main']['App']['GetInitialContent']();
}

export function Query(arg1, arg2, arg3) {
  return window['go']['main']['App']['Query'](arg1, arg2, arg3);
}
